config/routes.rb
    collection do
      get 'error'
      post 'get_card_information'
      get 'documentation'
      get 'select_payment_options'
      get 'select_payment_options_post'
      post 'checkout'
      post 'invoice_rtp_request'
      post 'test_webhook'
      get 'invoice_rtp_checkout'
    end
  end


  namespace :customers do
    resources :messages , only: [:index,:show,:new] do
      collection do
        post :save_chat
      end
    end
    resources :orders , only: [:index,:show]
    resources :disputes, only: [:index,:new,:create,:show] do
      collection do
        get 'update_tracker/:id' , to: "disputes#update_tracker" , as: :update_tracker
        get 'mail_generate_label/:id' , to: "disputes#mail_generate_label" , as: :mail_generate_label
        get 'update_notification/:id' , to: "disputes#update_notification" , as: :update_notification
      end
      resources :dispute_requests , only: [:update,:create]
    end
    resources :profiles , only: [:edit,:update] , path: '' do
      collection do
        get 'form_validate' , to: "profiles#form_validate"
      end
    end
  end


  resources :transactions, module: 'checkout'  do
    collection do
      post 'payment'
      post 'rtp_payment'
      get 'rtp_payment1'
      post 'rtp_payment_hook'
      get 'status'
    end
  end

  namespace :admins do
    resources :load_balancers, only: [:index, :new, :create, :edit, :update, :show] do
      collection do
        get 'update_load_balancer'
        post 'update_load_balancer'
      end
    end

    # get 'sales/index' , to: 'sales#index'
    # get 'sales/batch_detail' , to: 'sales#batch_detail'
    # get 'sales/qr_refund' , to: 'sales#qr_refund'
    # get 'sales/edit' , to: 'sales#edit'
    # get 'sales/refund_all' , to: 'sales#refund_all'
    # put 'sales/update' , to: 'sales#update'
    get 'locations/check_location_name'
    get 'mechant_bank_apis/index'
    get 'mechant_bank_apis/boltpay'
    get 'mechant_bank_apis/new'
    post 'mechant_bank_apis/create'
    get 'mechant_bank_apis/show'
    get 'mechant_bank_apis/edit'
    post 'mechant_bank_apis/update'
    get 'merchants/country_data'

    get :customer_disputes, to: "customer_disputes#customer_disputes"
    resources :customer_disputes, only: [:show]
    resources :messages, only: [:index,:show]
    # ---------sub-merchant-Admin Portal---------------
    get 'merchants/new_sub_merchant' , to:  'merchants#new_sub_merchant'
    post 'merchants/create_sub_merchant' , to:  'merchants#create_sub_merchant'
    get 'merchants/edit_sub_merchant' , to: 'merchants#edit_sub_merchant'
    put 'merchants/update_sub_merchant' , to: 'merchants#update_user_sub_merchant'
    get 'merchants/destroy_sub_merchant' , to: 'merchants#destroy_sub_merchant'

    resources :maxmind, only: [:show] do
      collection do
        get :edit
        post :update
      end
    end
    # ---------sub-merchant-Admin Portal---------------

    resources :plugin

    resources :admin_users do
        collection do
            get :get_data
            get :profile
        end
    end
    resources :affiliate_programs
    resources :reports, only: [] do
      collection do
        get :old_reports
        get :run_report
        get :autocomplete_location
        get :autocomplete_location_WR
        get :autocomplete_user
        get :autopopulate_partner
        get :autopopulate_affiliates
        post :generate_report
        get :generate_report
        get :search_user
        kinds = %w|chargeback sale gateway merchant wallet withdrawal terminal_id affiliate_program cbk_detail|
        get "index/:kind" => "reports#index", constraints: {kind: Regexp.new(kinds.join('|'))}
      end
    end

    resources :ach_gateways, only: [:index,:create,:edit,:update,:new] do
      collection do
        get 'archive_ach_gateway/:id', to:  "ach_gateways#archive", :as => :archive_ach_gateway
        get :archived_ach_gateways
        get 'block_ach_gateways/:id', to:  "ach_gateways#block_ach_gateways", :as => :block_ach_gateways
        get 'push_to_card' , to: "ach_gateways#push_to_card" , :as => :push_to_card
        get 'check' , to: "ach_gateways#check" , :as => :check
        get 'archive_push_to_card_gateway/:id', to:  "ach_gateways#archive", :as => :archive_push_to_card_gateway
        get 'archive_check_gateway/:id', to:  "ach_gateways#archive", :as => :archive_check_gateway
        get :archived_push_to_card_gateways
        get :archived_check_gateways
        get :check_gateway_existance
        # get :getverticaltype
        # get :getverticaltypenew
        # post :postverticaltype
      end
    end

    resources :slot_gateways, only: [:index,:create,:edit,:update,:new] do
      collection do
        get 'archive_slot_gateway/:id', to:  "slot_gateways#archive", :as => :archive_slot_gateway
        get :archived_slot_gateways
        get :validate_slot
        get :slot_management
        get :reset_slot_setting
        post :post_slot_management
        get 'block_slot_gateways/:id', to:  "slot_gateways#block_slot_gateways", :as => :block_slot_gateways
      end
    end

    resources :total_funds, only: [:index] do
      collection do
        get 'total_funds_search'
      end
    end


    resources :payment_gateways, only: [:index,:create,:edit,:update,:new] do
      collection do
        get 'archive_gateway/:id', to:  "payment_gateways#archive", :as => :archive_gateway
        get :archived_gateways
        get :unique_descriptor
        get 'block_gateways/:id', to:  "payment_gateways#block_gateways", :as => :block_gateways
        get 'specific_merchant', to:  'payment_gateways#specific_merchant'
        get :getverticaltype
        get :getverticaltypenew
        post :postverticaltype
        get :new_descriptor
        post :archive_descriptor
        post :create_descriptor
        get :old_gateways
      end
    end

    get 'transfers/index'
    get 'transfers/get_location_wallets'
    get 'transfers/get_merchant_location'
    get 'transfers/get_users'
    get 'transfers/get_user_details'
    post 'transfers/transfer_post'
    get 'transfers/get_wallet_name'
    resources :transfers, only: [] do
      get :autocomplete_user_name, on: :collection
    end

    resources :buy_rate, except: [:show] do
      collection do
        get :verify_admin
        get :verify_admin_password
      end
    end

    get 'buy_rate/getAgents'
    get 'buy_rate/getAffiliates'
    get 'buy_rate/getUsers'
    get 'buy_rate/getMerchantLocations'

    # ach
    get 'batch_checks', to: 'checks#batch_checks' , as: :batch_checks
    get 'check_batches', to: 'checks#check_batches' , as: :check_batches
    post 'check_batch_date', to: 'checks#check_batch_date' , as: :check_batch_date
    get :ach_index, :to => 'ach#index'
    get :under_review, :to => 'checks#under_review'
    get 'bulk_status_change', to: 'checks#bulk_status_change' , as: :bulk_status_change

    # post :instant_pay_batch_date, :to=>'instant_pay#instant_pay_batch_date',as: :member

    post :ach_batch_date, :to=>'instant_pay#ach_batch_date',as: :member
    get :ach_approved, :to => 'ach#ach_approved'
    get 'ach/new',  :to => 'ach#new'
    get 'ach/:id/approve', to: 'ach#approve',as: 'ach_approve'
    get 'ach/batches'
    get 'selected_locations', :to => 'ach#selected_locations'
    get 'location_data', :to => 'ach#location_data'
    # post 'create_ach', :to => 'ach#create_ach'

    #instant pay
    get :instant_pay_verify_phone_number, :to => 'instant_pay#verify_phone_number'
    get :instant_pay_verification, :to => 'instant_pay#verification'
    get :instant_pay_index, :to => 'instant_pay#index'
    # post :instant_pay_index, :to => 'instant_pay#index'
    post :instant_pay_batch_date, :to=>'instant_pay#instant_pay_batch_date',as: :instant_member
    get :approve_debit_card_deposit, :to => 'checks#approve_debit_card_deposit'
    get 'instant_pay/new',  :to => 'instant_pay#new'
    get :instant_pay_approved, :to => 'instant_pay#instant_pay_approved'
    get 'instant_pay/:id/approve', to: 'instant_pay#approve',as: 'instant_approve'
    put :update_name, :to => 'instant_pay#update_name'
    put 'instant_pay/update', :to => 'instant_pay#update', as: :instant_pay_update
    get 'instant_pay/batches'
    get 'instant_pay/selected_locations', :to => 'instant_pay#selected_locations'
    get 'instant_pay/location_data', :to => 'instant_pay#location_data'
    # post 'create_instant_pay', :to => 'instant_pay#create_instant_pay'
    get 'instant_pay/bulk_status_change', to: 'instant_pay#bulk_status_change' , as: :instant_pay_bulk_status_change

    #= instant_ach
    get :instant_ach_verify_phone_number, :to => 'instant_ach#verify_phone_number'
    get :instant_ach_verification, :to => 'instant_ach#verification'
    get :instant_ach_index, :to => 'instant_ach#index'
    post :instant_ach_export, :to => 'instant_ach#export'
    post :instant_ach_batch_date, :to=>'instant_ach#instant_ach_batch_date',as: :instant_ach_member
    get :instant_ach_approved, :to => 'instant_ach#instant_ach_approved'
    get :d_date, :to => 'instant_ach#d_date'
    put :update_recipient, :to => 'instant_ach#update_recipient'
    get 'instant_ach/new',  :to => 'instant_ach#new'
    get 'instant_ach/:id/approve', to: 'instant_ach#approve',as: 'instant_ach_approve'
    get 'instant_ach/batches'
    get 'instant_ach/selected_locations', :to => 'instant_ach#selected_locations'
    get 'instant_ach/location_data', :to => 'instant_ach#location_data'
    # post 'create_instant_ach', :to => 'instant_ach#create_instant_ach'
    get 'instant_ach/achs_search'
    get 'instant_ach/batches_search'
    get 'instant_ach/bulk_status_change'
    get :approve_ach_request, to: 'instant_ach#approve_ach_request'
    get :edit_bank_details, to: 'instant_ach#edit_bank_details'
    post :update_bank_details, :to => 'instant_ach#update_bank_details'
    get :approve_request, to: 'instant_ach#approve_request'
    get :image_delete, to: 'instant_ach#image_delete'

app/controllers/admins/partners_controller.rb
class Admins::PartnersController < AdminsController
  skip_before_action :check_admin
  def index
    @partner = User.new
    @partners = User.partner
    respond_to do |format|
      format.html{ render :index}
      format.json { render json: PartnersDatatable.new(view_context, @partners)}
    end
  end

  def new
    render template: 'admins/partners/new'
  end

  def create
    @partner = User.new(new_partner_params)
    @merchant=User.find params[:user][:merchant_id]
    @partner.regenerate_token
    if @partner.partner!
      @merchant.partner= @partner
      respond_to do |format|
        format.html{
          flash[:success] = 'Partner has been added Successfully!'
        }
      end
    else
      flash[:error] = @partner.errors.full_messages.first
    end
    redirect_back(fallback_location: root_path)
  end

  def edit
    @partner= User.find params[:id]
    respond_to :js
  end

  def update
    partner = User.find params[:id]
    partner.update(edit_partner_params )
    if partner.errors.blank?
      flash[:success] = "Partner has been updated Successfully"
      redirect_back(fallback_location: root_path)
    else
      flash[:error] = "Error occured in Edit"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
  end

  private

  def new_partner_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name ,:postal_address  , :phone_number , :status,  :merchant_id, :first_name, :last_name,)
  end

  def edit_partner_params
    params.require(:user).permit(:id ,:email, :password, :password_confirmation, :name ,:postal_address  , :phone_number , :status,  :merchant_id, :first_name, :last_name,)
  end
end

app/controllers/v2/partner/exports_controller.rb
class V2::Partner::ExportsController < V2::Partner::BaseController
  include Zipline
  def index
    page_size = params[:filter].present? ? params[:filter].to_i : 10
    Report.where(file_id: nil).update_all(read: true)
    user_id = current_user.merchant_id.present? ? current_user.merchant_id : current_user.id
    if params[:query].present?
      conditions = []
      parameters = []
      conditions << "name ILIKE ? OR report_type ILIKE ?"
      parameters << "%#{params[:query]}%"
      parameters << "%#{params[:query].parameterize(separator: "_")}%"
      conditions = [conditions.join(" AND "), *parameters]
    end
    if params[:search].present?
      status_array = params[:search].select{|k,v| v=="1"}.keys.map{|a| a.downcase}
    elsif params["no_data"]=="no_data"
      status_array = []
    else
      status_array = ["completed","pending"]
    end
    @files = Report.where(user_id: user_id, status: status_array , read: [false,true]).where(conditions).order(id: :desc).per_page_kaminari(params[:page]).per(page_size)
    render partial: "v2/partner/shared/exported_datatable" if request.xhr?
  end

  def export_download
    if params[:report_id].present?
      report = Report.find_by(id: params[:report_id])
      report.update(read: true) if report.present?
    end
    if params[:id].present?
      files = []
      ids = JSON(params[:id])
      if ids.present?
        if ids.class == Array
          if ids.count == 1
            foo = QcFile.find(ids.first)
            data = open("https:"+foo.image.url)
            send_data data.read, filename: "#{foo.image_file_name}", type: "text/csv", disposition: 'attachment'
          else
            QcFile.where(id: ids).each do|foo|
              files.push([foo.image, "#{foo.id}#{foo.image_file_name}", modification_time: 1.day.ago])
            end
            zipline(files, 'export.zip')
          end
        else
          foo = QcFile.find(params[:id])
          data = open("https:"+foo.image.url)
          send_data data.read, filename: "#{foo.image_file_name}", type: "text/csv", disposition: 'attachment'
        end
      end
    end
  end

end

app/controllers/v2/partner/settings_controller.rb
class V2::Partner::SettingsController < V2::Partner::BaseController
	def fee_structure
		@user = current_user
		fee = current_user.fees
		@user_data = fee.try(:high).first
		@buyrate_dispensary = fee.try(:low).first
		system_fee = current_user.system_fee
		@withdraw_fee = system_fee["gitcard_fee"].to_f + system_fee["ach_dollar"].to_f + system_fee["send_check"].to_f + system_fee["push_to_card_dollar"].to_f
		@failed_ach_check = system_fee["failed_ach_fee"].to_f + system_fee["failed_check_fee"].to_f
	end
end

app/helpers/admins/partners_helper.rb
module Admins::PartnersHelper
end

app/helpers/v2/partner/accounts_helper.rb
module V2::Partner::AccountsHelper
  def manage_partner_batches(iso_wallet_id, agent_wallet_id, affiliate_wallet_id, date,type, iso_starting_balance = nil, agent_starting_balance = nil, affiliate_starting_balance = nil)
    TransactionBatch.create(
        iso_wallet_id: iso_wallet_id,
        agent_wallet_id: agent_wallet_id,
        affiliate_wallet_id: affiliate_wallet_id,
        iso_balance: iso_starting_balance.to_f,
        agent_balance: agent_starting_balance.to_f,
        affiliate_balance: affiliate_starting_balance.to_f,
        batch_date: date,
        batch_type: type,
    )
  end

  def partner_percentage(original_number, new_number)
    if original_number.to_f > 0
      new_value = new_number.to_f - original_number.to_f
      number_with_precision((new_value/original_number) * 100, precision: 2, delimiter: ',')
    else
      number_with_precision(0, precision: 2)
    end
  end
end

app/views/v2/partner/push_to_card/index.html.erb
<% sequence_down = AppConfig.try(:sequence_down).try(:first) %>
<% p2c = AppConfig.try(:p2c).try(:first) %>
<% if (sequence_down.present? && sequence_down.boolValue == true) || (ENV['SEQUENCE_DOWN'].present? && ENV['SEQUENCE_DOWN'] == "true") %>
  <%= render 'shared/maintenance_modal', locals: {title: 'System Maintenance', body: 'We apologize for the inconvenience, however this feature is not available at this time as we are having issues with our Blockchain'} %>
<% elsif (p2c.present? && p2c.boolValue == false)  %>
  <%= render 'shared/maintenance_modal', locals: {title: 'Pushed To Card is Blocked', body: 'We apologize for the inconvenience, however this feature is not available at this time as Push To Card is Inactive.'} %>
<% elsif @user.push_to_card  %>
  <%= render 'shared/maintenance_modal', locals: {title: 'Disabled Withdraw', body: 'We apologize for the inconvenience, but this feature is currently  unavailable at this time. Please email Support@gareenboxpos.com for all your inquiries. Thank you!'} %>
<% else %>
  <%= render 'shared/maintenance_modal', locals: {title: 'Merchant is Blocked', body: 'We apologize for the inconvenience, however this feature is not available at this time as Merchant is Inactive.'} %>
<% end %>

<div class="m-subheader">
  <div class="d-flex align-items-center">
    <div class="mr-auto">
      <ul class="m-subheader__breadcrumbs m-nav m-nav--inline set-path">
        <li class="m-nav__item">
          <a href="#" class="m-nav__link">
            <span class="my-order-nav">
                Withdraw
            </span>
          </a>
        </li>
        <li class="m-nav__separator">
          <%= image_tag "v2/merchant/icons/angle.svg"%>
        </li>
        <li class="m-nav__item">
          <a href="<%= v2_partner_push_to_card_index_path %>" class="m-nav__link">
              <span class="order-active">
                Push to Card
              </span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="m-content">
  <div class="m-portlet m-portlet--mobile m-portal_datatable">
    <h3 class="m-subheader__title col-lg-12 ach-heading-custom flex-line flex-between">
      Push to Card
      <div class="actions-header">
        <button type="button" class="btn m-btn--pill btn-secondary activity_log__btn slide-toggle slide-toggle-open" data-type="push_to_card">
          <span class="activity-log-text">Activity Log </span><%= image_tag "v2/activity_log/noun_clock_1698764.svg", class: "timer-width-18 activity-log-timer" %>
        </button>
        <button type="button" class="btn m-btn--pill btn-secondary ml-4 mr-4 export_bulk export-btn" data-toggle="modal" data-target="#echeckModal">
          Export
        </button>
        <%#= link_to "orignal", new_ach_path , class: "btn m-btn--pill color-ffd95a" ,data: {dismiss: "modal",toggle: "modal",target: "#profileModel"} %>
        <% if (sequence_down.present? && sequence_down.boolValue == true) || (ENV['SEQUENCE_DOWN'].present? && ENV['SEQUENCE_DOWN'] == "true") %>
          <button type="button" data-toggle="modal" data-target="#maintenance-modal" class="prevent_halt btn m-btn--pill new-ach-button color-ffd95a">Create
            New
          </button>
        <% elsif (p2c.present? && p2c.boolValue == false)  %>
          <button type="button" data-toggle="modal" data-target="#maintenance-modal" class="prevent_halt btn m-btn--pill new-ach-button color-ffd95a">Create
            New
          </button>
        <% else %>
          <% if @push_to_card && !@user.push_to_card %>
            <button class="prevent_halt btn m-btn--pill new-ach-button color-ffd95a btn-preview-invoice show-dynamic-modal show-cover-spin" id="view_detail" data-modal_container_selector="#new_check_modal" data-modal_selector="#newP2CModal" data-url="<%= debit_card_deposit_form_v2_partner_push_to_card_index_path %>" data-method="GET">
              New
              P2C
            </button>
          <% else %>
            <button type="button" data-toggle="modal" data-target="#maintenance-modal" class="prevent_halt btn m-btn--pill new-ach-button color-ffd95a">Create
              New
            </button>
          <% end %>
        <% end %>
      </div>
    </h3>


    <div class="m-portlet m-portlet--mobile m-portal_datatable">
      <div class="m-portlet__body">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 charge_back_widget mb-4">

          <div class="row md">
            <div class="col-xl-10 col-lg-10 col-md-10 col-sm-12 col-xs-12">
              <div class="title">

              </div>
            </div>
            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-12 col-xs-12">
              <div class='input-group pull-right rotate--icon mt-3' id='push_to_card'>
                <input type='text' class="form-control m-input day-btn" readonly placeholder="Today"/>
                <input type='hidden' value="date" id="detail-value"/>
                <div class="input-group-append day-btn">
            													<span class="input-group-text">
            														<%= image_tag "v2/merchant/icons/down-b.svg", class: 'rotate', id: 'img--remove' %>
            													</span>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-6 col-xs-12 margin--top-10 ach-echeck">
              <div class="row">
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-xs-3">
                  <div class="icon-div">
                    <%= image_tag "v2/merchant/icons/earnings.svg"%>
                  </div>
                </div>
                <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9 col-xs-9 padding-0-left unpaid-padding">
                  <div class="small_chargeback">Total Paid</div>
                  <div id="total_paid" class="price_chargeback">$<%= number_with_precision(@total_paid, precision: 2, delimiter: ',') %></div>
                </div>
              </div>
            </div>
            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-6 col-xs-12 margin--top-10 ach-echeck">
              <div class="row">
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-xs-3">
                  <div class="icon-div">
                    <%= image_tag "v2/merchant/icons/processingfee.svg"%>
                  </div>
                </div>
                <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9 col-xs-9 padding-0-left unpaid-padding">
                  <div class="small_chargeback">Total Pending</div>
                  <div id="total_pending"  class="price_chargeback">$<%= number_with_precision(@total_pending, precision: 2, delimiter: ',') %></div>
                </div>
              </div>
            </div>

            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-6 col-xs-12 margin--top-10 ach-echeck">
              <div class="row">
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-xs-3">
                  <div class="icon-div">
                    <%= image_tag "v2/merchant/icons/processingfee.svg"%>
                  </div>
                </div>
                <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9 col-xs-9 padding-0-left unpaid-padding">
                  <div class="small_chargeback">Total Paid by Wire</div>
                  <div id="total_paid_wire"  class="price_chargeback">$<%= number_with_precision(@total_paid_wire, precision: 2, delimiter: ',') %></div>
                </div>
              </div>
            </div>


            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-6 col-xs-12 margin--top-10 ach-echeck">
              <div class="row">
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-xs-3">
                  <div class="icon-div">
                    <%= image_tag "v2/merchant/icons/expensis.svg"%>
                  </div>
                </div>
                <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9 col-xs-9 padding-0-left unpaid-padding">
                  <div class="small_chargeback">Total Void</div>
                  <div  id="total_void"  class="price_chargeback">$<%= number_with_precision(@total_void, precision: 2, delimiter: ',') %></div>
                </div>
              </div>
            </div>
            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-6 col-xs-12 margin--top-10 ach-echeck">
              <div class="row">
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-xs-3">
                  <div class="icon-div">
                    <%= image_tag "v2/merchant/icons/money.svg"%>
                  </div>
                </div>
                <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9 col-xs-9 padding-0-left unpaid-padding">
                  <div class="small_chargeback">Total Failed</div>
                  <div id="total_failed"  class="price_chargeback">$<%= number_with_precision(@total_failed, precision: 2, delimiter: ',') %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!--begin: Datatable -->
        <%# render partial: "v2/merchant/shared/datatable_search" %>
        <%# render partial: "v2/merchant/shared/datatable_search",locals: {filter_path: v2_partner_push_to_card_index_path, search_id: "client_search"} %>

          <div class="row">
            <div class="col-md-6 col-sm-12">
              <div class="select_number mb-0">
                  <div class="mt-3 mr-2">
                      Show
                  </div>
                    <div class="dropdown bootstrap-select form-control m-bootstrap-select m-bootstrap-select--pill m_ pagination_dropdown">
                      <%= form_tag v2_partner_push_to_card_index_path, method: :get, id:'push_to_card_filter' do  %>
                        <div id="show--entries">
                         <%= select_tag "filter", options_for_select(@filters.map{|v|[v]}, selected: params[:filter].present? ? params[:filter] : "10") ,
                          :prompt => false,
                          :required => true,
                          class: "form-control m-bootstrap-select m-bootstrap-select--pill m_selectpicker pagination_dropdown",
                          data: {confirm: "Are you sure ?"}
                         %>
                         <%= hidden_field_tag :wallet_id ,params[:wallet_id] %>
                        </div>
                      <% end %>
                    </div>
                    <div class="m--space-10"></div>
                    <span class="mt-3 ml-2">
                      Entries
                    </span>
              </div>
            </div>
            <div class="col-md-6 col-sm-12">
              <%= form_for :q , url: "/v2/partner/push_to_card" , html: {method: 'GET'}  do |f| %>
                <div class="m-form__group">
                  <div class="m-input-icon m-input-icon--left m-input-icon_datatable">
                    <%= f.search_field :name_cont , class: "form-control m-input search_input_datatable" , placeholder: "Search" , value: params[:q].try(:[],"name_cont")%>
                     <%= hidden_field_tag :wallet_id ,params[:wallet_id] %>
                    <span class="m-input-icon__icon m-input-icon__icon--left">
                      <span>
                        <%= image_tag "v2/merchant/datatable/search.svg", class: 'win-img' %>
                      </span>
                    </span>

                  </div>
                </div>
                 
            <% end %>
            </div>
          </div>


        <div class="table-data">
          <%= render partial: "v2/partner/push_to_card/push_2_card_datatable" %>
        </div>
      </div>
    </div>

    <div class="m-portlet__body">
      <!--      Exported Files-->
      <!--begin: Datatable -->
      <%#= render partial: "datatable" %>
      <%#= render partial: "shared/datatable" %>
    </div>
  </div>
  <!-- END EXAMPLE TABLE PORTLET-->
</div>
<section id="new_check_modal"></section>
<section id="p2c_detail_modal"></section>
<%= render 'v2/partner/push_to_card/p2c_void_modal' %>
<%= render 'v2/partner/push_to_card/p2c_void_success' %>
<%= render 'v2/partner/shared/error_modal' %>
<%# render partial: "new" %>
<%= render partial: "confirm_p2c_modal" %>
<%= render partial: "p2c_success" %>
<%#= render partial: "profile/create_password" %>
<%= javascript_include_tag 'v2/merchant/bootstrap-daterangepicker' %>
<%= javascript_include_tag 'v2/partner/push_to_card' %>
<%= stylesheet_link_tag 'v2/partner/push_to_card' %>
<%= render partial: 'v2/merchant/shared/export_modal', locals: {title: "Export P2C", type: TypesEnumLib::WorkerType::InstantPAY} %>
<%#= render partial: 'v2/merchant/shared/export_modal', locals: {title: "Export E-Checks", type: TypesEnumLib::WorkerType::InstantPAY} %>