config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'messages/index'
    get 'messages/show'
    resources :emails do
      collection do
        get :export
        get :delete_schedule
        post :resend
        get :resend_email
      end
    end
  end

  require 'sidekiq/web'

  root :to => 'home#index'
  
  # ActionCable mounted for microservice comms
  mount ActionCable.server => '/cable'
  # Sidekiq mounted for background queueing dashboard
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'contacts/message'
  get 'update_valid/:id', to: 'admins#update_valid', as: :update_valid_app

  resources :checkout, module: 'checkout', only: [:index,:new] do
    collection do
      get 'error'
      post 'get_card_information'
      get 'documentation'
      get 'select_payment_options'
      get 'select_payment_options_post'
      post 'checkout'
      post 'invoice_rtp_request'
      post 'test_webhook'
      get 'invoice_rtp_checkout'
    end
  end


  namespace :customers do
    resources :messages , only: [:index,:show,:new] do
      collection do
        post :save_chat
      end
    end
    resources :orders , only: [:index,:show]
    resources :disputes, only: [:index,:new,:create,:show] do
      collection do
        get 'update_tracker/:id' , to: "disputes#update_tracker" , as: :update_tracker
        get 'mail_generate_label/:id' , to: "disputes#mail_generate_label" , as: :mail_generate_label
        get 'update_notification/:id' , to: "disputes#update_notification" , as: :update_notification
      end
      resources :dispute_requests , only: [:update,:create]
    end
    resources :profiles , only: [:edit,:update] , path: '' do
      collection do
        get 'form_validate' , to: "profiles#form_validate"
      end
    end
  end


  resources :transactions, module: 'checkout'  do
    collection do
      post 'payment'
      post 'rtp_payment'
      get 'rtp_payment1'
      post 'rtp_payment_hook'
      get 'status'
    end
  end

  namespace :admins do
    resources :load_balancers, only: [:index, :new, :create, :edit, :update, :show] do
      collection do
        get 'update_load_balancer'
        post 'update_load_balancer'
      end
    end

    # get 'sales/index' , to: 'sales#index'
    # get 'sales/batch_detail' , to: 'sales#batch_detail'
    # get 'sales/qr_refund' , to: 'sales#qr_refund'
    # get 'sales/edit' , to: 'sales#edit'
    # get 'sales/refund_all' , to: 'sales#refund_all'
    # put 'sales/update' , to: 'sales#update'
    get 'locations/check_location_name'
    get 'mechant_bank_apis/index'
    get 'mechant_bank_apis/boltpay'
    get 'mechant_bank_apis/new'
    post 'mechant_bank_apis/create'
    get 'mechant_bank_apis/show'
    get 'mechant_bank_apis/edit'
    post 'mechant_bank_apis/update'
    get 'merchants/country_data'

    get :customer_disputes, to: "customer_disputes#customer_disputes"
    resources :customer_disputes, only: [:show]
    resources :messages, only: [:index,:show]
    # ---------sub-merchant-Admin Portal---------------
    get 'merchants/new_sub_merchant' , to:  'merchants#new_sub_merchant'
    post 'merchants/create_sub_merchant' , to:  'merchants#create_sub_merchant'
    get 'merchants/edit_sub_merchant' , to: 'merchants#edit_sub_merchant'
    put 'merchants/update_sub_merchant' , to: 'merchants#update_user_sub_merchant'
    get 'merchants/destroy_sub_merchant' , to: 'merchants#destroy_sub_merchant'

    resources :maxmind, only: [:show] do
      collection do
        get :edit
        post :update
      end
    end
    # ---------sub-merchant-Admin Portal---------------

    resources :plugin

    resources :admin_users do
        collection do
            get :get_data
            get :profile
        end
    end
    resources :affiliate_programs
    resources :reports, only: [] do
      collection do
        get :old_reports
        get :run_report
        get :autocomplete_location
        get :autocomplete_location_WR
        get :autocomplete_user
        get :autopopulate_partner
        get :autopopulate_affiliates
        post :generate_report
        get :generate_report
        get :search_user
        kinds = %w|chargeback sale gateway merchant wallet withdrawal terminal_id affiliate_program cbk_detail|
        get "index/:kind" => "reports#index", constraints: {kind: Regexp.new(kinds.join('|'))}
      end
    end

    resources :ach_gateways, only: [:index,:create,:edit,:update,:new] do
      collection do
        get 'archive_ach_gateway/:id', to:  "ach_gateways#archive", :as => :archive_ach_gateway
        get :archived_ach_gateways
        get 'block_ach_gateways/:id', to:  "ach_gateways#block_ach_gateways", :as => :block_ach_gateways
        get 'push_to_card' , to: "ach_gateways#push_to_card" , :as => :push_to_card
        get 'check' , to: "ach_gateways#check" , :as => :check
        get 'archive_push_to_card_gateway/:id', to:  "ach_gateways#archive", :as => :archive_push_to_card_gateway
        get 'archive_check_gateway/:id', to:  "ach_gateways#archive", :as => :archive_check_gateway
        get :archived_push_to_card_gateways
        get :archived_check_gateways
        get :check_gateway_existance
        # get :getverticaltype
        # get :getverticaltypenew
        # post :postverticaltype
      end
    end

    resources :slot_gateways, only: [:index,:create,:edit,:update,:new] do
      collection do
        get 'archive_slot_gateway/:id', to:  "slot_gateways#archive", :as => :archive_slot_gateway
        get :archived_slot_gateways
        get :validate_slot
        get :slot_management
        get :reset_slot_setting
        post :post_slot_management
        get 'block_slot_gateways/:id', to:  "slot_gateways#block_slot_gateways", :as => :block_slot_gateways
      end
    end

    resources :total_funds, only: [:index] do
      collection do
        get 'total_funds_search'
      end
    end


    resources :payment_gateways, only: [:index,:create,:edit,:update,:new] do
      collection do
        get 'archive_gateway/:id', to:  "payment_gateways#archive", :as => :archive_gateway
        get :archived_gateways
        get :unique_descriptor
        get 'block_gateways/:id', to:  "payment_gateways#block_gateways", :as => :block_gateways
        get 'specific_merchant', to:  'payment_gateways#specific_merchant'
        get :getverticaltype
        get :getverticaltypenew
        post :postverticaltype
        get :new_descriptor
        post :archive_descriptor
        post :create_descriptor
        get :old_gateways
      end
    end

    get 'transfers/index'
    get 'transfers/get_location_wallets'
    get 'transfers/get_merchant_location'
    get 'transfers/get_users'
    get 'transfers/get_user_details'
    post 'transfers/transfer_post'
    get 'transfers/get_wallet_name'
    resources :transfers, only: [] do
      get :autocomplete_user_name, on: :collection
    end

    resources :buy_rate, except: [:show] do
      collection do
        get :verify_admin
        get :verify_admin_password
      end
    end

    get 'buy_rate/getAgents'
    get 'buy_rate/getAffiliates'
    get 'buy_rate/getUsers'
    get 'buy_rate/getMerchantLocations'

    # ach
    get 'batch_checks', to: 'checks#batch_checks' , as: :batch_checks
    get 'check_batches', to: 'checks#check_batches' , as: :check_batches
    post 'check_batch_date', to: 'checks#check_batch_date' , as: :check_batch_date
    get :ach_index, :to => 'ach#index'
    get :under_review, :to => 'checks#under_review'
    get 'bulk_status_change', to: 'checks#bulk_status_change' , as: :bulk_status_change

    # post :instant_pay_batch_date, :to=>'instant_pay#instant_pay_batch_date',as: :member

    post :ach_batch_date, :to=>'instant_pay#ach_batch_date',as: :member
    get :ach_approved, :to => 'ach#ach_approved'
    get 'ach/new',  :to => 'ach#new'
    get 'ach/:id/approve', to: 'ach#approve',as: 'ach_approve'
    get 'ach/batches'
    get 'selected_locations', :to => 'ach#selected_locations'
    get 'location_data', :to => 'ach#location_data'
    # post 'create_ach', :to => 'ach#create_ach'

    #instant pay
    get :instant_pay_verify_phone_number, :to => 'instant_pay#verify_phone_number'
    get :instant_pay_verification, :to => 'instant_pay#verification'
    get :instant_pay_index, :to => 'instant_pay#index'
    # post :instant_pay_index, :to => 'instant_pay#index'
    post :instant_pay_batch_date, :to=>'instant_pay#instant_pay_batch_date',as: :instant_member
    get :approve_debit_card_deposit, :to => 'checks#approve_debit_card_deposit'
    get 'instant_pay/new',  :to => 'instant_pay#new'
    get :instant_pay_approved, :to => 'instant_pay#instant_pay_approved'
    get 'instant_pay/:id/approve', to: 'instant_pay#approve',as: 'instant_approve'
    put :update_name, :to => 'instant_pay#update_name'
    put 'instant_pay/update', :to => 'instant_pay#update', as: :instant_pay_update
    get 'instant_pay/batches'
    get 'instant_pay/selected_locations', :to => 'instant_pay#selected_locations'
    get 'instant_pay/location_data', :to => 'instant_pay#location_data'
    # post 'create_instant_pay', :to => 'instant_pay#create_instant_pay'
    get 'instant_pay/bulk_status_change', to: 'instant_pay#bulk_status_change' , as: :instant_pay_bulk_status_change

    #= instant_ach
    get :instant_ach_verify_phone_number, :to => 'instant_ach#verify_phone_number'
    get :instant_ach_verification, :to => 'instant_ach#verification'
    get :instant_ach_index, :to => 'instant_ach#index'
    post :instant_ach_export, :to => 'instant_ach#export'
    post :instant_ach_batch_date, :to=>'instant_ach#instant_ach_batch_date',as: :instant_ach_member
    get :instant_ach_approved, :to => 'instant_ach#instant_ach_approved'
    get :d_date, :to => 'instant_ach#d_date'
    put :update_recipient, :to => 'instant_ach#update_recipient'
    get 'instant_ach/new',  :to => 'instant_ach#new'

app/controllers/merchant/apps_controller.rb
class Merchant::AppsController < Merchant::BaseController

  def index
    @heading = 'Apps'
    if current_user.merchant_id.present? 
      @apps=OauthApp.where(user_id: current_user.merchant_id).per_page_kaminari(params[:page]).per(10).order("id DESC")
    else
      @apps=OauthApp.where(user_id: current_user.id).per_page_kaminari(params[:page]).per(10).order("id DESC")
    end
  end

  def create
    @app = OauthApp.new(app_params)
    if current_user.merchant_id.present? && current_user.submerchant_type == "admin_user"
      @app.user_id = current_user.merchant_id
    else
      @app.user_id = current_user.id
    end
    @app.key = 'ID' + random_token
    @app.secret = 'SE' + random_token
    @app.token = random_token
    if @app.save
      flash[:notice] = I18n.t 'merchant.controller.app_created'
      if current_user.MERCHANT?
        redirect_back(fallback_location: root_path)
      else
        redirect_back(fallback_location: root_path)
      end
    else
      flash[:notice] = I18n.t 'merchant.controller.app_saving'
      redirect_back(fallback_location: root_path)
    end
  end

  def new
  end

  def edit
  end

  def update
    @heading = "Application Settings"
    @app = OauthApp.find(params[:id])
    @app.update(key: 'ID' + random_token,secret:  'SE' + random_token ,token: random_token)
    respond_to :js
  end

  def show
    @heading = "Application Settings"
    @app = OauthApp.find params[:id]
  end

  def destroy
    @app = OauthApp.find(params[:id])
    if @app.destroy
      flash[:notice] = I18n.t 'merchant.controller.app_del'
      redirect_to root_path
    end
  end

  def show_app
    @app = OauthApp.find(params[:user_id])
    render partial: 'shared/app_modal', locals: { user: @app }
  end

  def update_valid
    @app = OauthApp.find(params[:id])
    @app.is_block = params[:is_block]
    @app.save(:validate => false)
  end

  private

  def app_params
    params.require(:oauth_app).permit(:name, :description, :redirect_uri, :website, :privacy_url, :tos, :organization_name, :organization_web)
  end
end

app/controllers/merchant/bank_controller.rb
class Merchant::BankController < Merchant::BaseController

  def index
    @banks =  BankDetail.all.order(id: :desc)
    @iv       = 'a2xhcgAAAAAAAAAA'
    @password = Digest::SHA256.digest("#{ENV['BANK_ECRYPTION_CODE']}")
    #bank = BankDetail.first
  end

  def create
    bank_name = params[:bank_name]
    account_name = params[:account_name]
    account_no = params[:account_no]
    routing_no = params[:routing_no]
    account_digits = account_no.split(//).last(4).join
    routing_digits = routing_no.split(//).last(4).join
    enc_account_no = AESCrypt.encrypt("#{ENV['BANK-ENCRYPTION-CODE']}",  account_no)
    enc_routing_no = AESCrypt.encrypt("#{ENV['BANK-ENCRYPTION-CODE']}",  routing_no)
    BankDetail.create! bank_name: bank_name, account_name: account_name, account_no: enc_account_no, routing_no: enc_routing_no, account_digit: account_digits, routing_digit: routing_digits
    flash[:success] = I18n.t 'merchant.controller.bank_detail'
    redirect_to merchant_bank_index_path
  end
end

app/controllers/merchant/customer_disputes_controller.rb
class Merchant::CustomerDisputesController < Merchant::BaseController

  def index
    @customer_disputes = @user.disputes_as_merchant
  end

  def show
    @customer_dispute = CustomerDispute.find(params[:id])
    @transaction = @customer_dispute.dispute_transaction
    @tracker = @transaction.tracker
    @customer = @customer_dispute.customer
    @dispute_request_first = @customer_dispute.dispute_requests.first
    @dispute_requests_last = @customer_dispute.dispute_requests.last
    @merchant_offer = @customer_dispute.dispute_requests.where(request_type: "merchant_offer").first
    @final_merchant_offer = @customer_dispute.dispute_requests.where(request_type: "merchant_final_offer").last
    @pending_counter_offer = @customer_dispute.dispute_requests.where(user_id: @customer_dispute.customer_id,status: "pending",title: "Counteroffer").last
    @customer_offer =  @customer_dispute.dispute_requests.where(request_type: "counter_offer").last
    @return_to_sender = @customer_dispute.dispute_requests.where(request_type: "return_to_sender").last
    # TODO there should be only 1 pending dispute_requests
    render partial: 'show'
  end

end

app/controllers/merchant/maxmind_controller.rb
class Merchant::MaxmindController < Merchant::BaseController
  include Merchant::MaxmindHelper

  def index
    page_size = params[:tx_maxmind_filter].present? ? params[:tx_maxmind_filter].to_i : 10
    @filters = [10,25,50,100]
    @risk_evaluation_status= [{value: "reject_manual_review", view:"Rejected by manual review"}, {value: "pending_manual_review", view: "Pending Manual Review"}, {value: "expired_manual_review", view: "Manual Review Expired"}, {value: "accept_manual_review", view: "Accepted by Manual Review"}, {value: "accept_default", view: "Accepted by default"}]
    if current_user.merchant_id.present?
      @user_wallets = @user.wallets.primary.where.not(location_id: nil)
    else
      @user_wallets = @user.wallets.primary
    end

    if params.present? && params["query"].present?
      if params["query"]["date"].present? || params["risk_status"].present?
        conditions = transactions_search_query_maxmind_merchant(params)

        if conditions.present?
          @manual_review_transactions = Transaction.joins(:minfraud_result).where(receiver_wallet_id: @user_wallets.pluck(:id)).where(conditions).order(created_at: :desc).per_page_kaminari(params[:page]).per(page_size)
        else
          @manual_review_transactions = Transaction.joins(:minfraud_result).where(receiver_wallet_id: @user_wallets.pluck(:id)).order(created_at: :desc).per_page_kaminari(params[:page]).per(page_size)
        end
      else
        @manual_review_transactions = Transaction.joins(:minfraud_result).where(receiver_wallet_id: @user_wallets.pluck(:id)).order(created_at: :desc).per_page_kaminari(params[:page]).per(page_size)
      end
    else
      @manual_review_transactions = Transaction.joins(:minfraud_result).where(receiver_wallet_id: @user_wallets.pluck(:id)).order(created_at: :desc).per_page_kaminari(params[:page]).per(page_size)
    end
  end

  def show
    @minfraud_result = MinfraudResult.find params[:id]
    @minfraud_insight = @minfraud_result.insight_detail

    render :partial => "show"
  end

  def update
    @minfraud_result = MinfraudResult.find params[:id]
    if @minfraud_result.qc_action == TypesEnumLib::RiskType::PendingReview &&
        @minfraud_result.qc_reason == TypesEnumLib::RiskReason::ManualReview
      if params[:new_action] == "a"
        @minfraud_result.qc_action = TypesEnumLib::RiskType::Accept
        @minfraud_result.save
        flash[:success] = I18n.t('maxmind.accepted')
      elsif params[:new_action] == "r"

        #Refunding transactions start
        transaction = Transaction.find(@minfraud_result.transaction_id)
        merch = transaction.receiver
        refund = RefundHelper::RefundTransaction.new(transaction.seq_transaction_id, transaction,merch,nil,"Manual Reject by Merchant", @user)
        response = refund.process
        #Refunding transactions end

        if response[:success] == true
          @minfraud_result.qc_action = TypesEnumLib::RiskType::Reject
          @minfraud_result.save
          flash[:success] = I18n.t('maxmind.rejected')
        else
          flash[:error] = response[:message]
        end
      else
        flash[:error] = I18n.t('maxmind.invalid_params')
      end
    else
      flash[:error] = I18n.t('maxmind.invalid_request')
    end
    #redirect_back(fallback_location: root_path)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js
    end
  end

end

app/controllers/merchant/plugins_controller.rb
class Merchant::PluginsController < Merchant::BaseController
  layout 'merchant'
  def index
    @plugins=Asset.all
  end
end

app/views/admins/merchants/_edit_documentation.html.erb
<input type="hidden" name="form_data" value="<%= params[:form_data].to_json %>">
<input type="hidden" name="format" value="<%= params[:format].present? ? params[:format] : '' %>">
<% if @images.present? %>
  <% @images.each do |image| %>
    <% @owner_id_card = @images.map{|v| v.image_type == Documentation.types[:owner_id_card]? v:nil}.compact %>
  <%end %>
  <% @images.each do |image| %>
    <% @w9 = @images.map{|v| v.image_type == Documentation.types[:w9]? v:nil}.compact %>
  <%end %>
  <% @images.each do |image| %>
    <% @ein = @images.map{|v| v.image_type == Documentation.types[:ein] || Documentation.types[:ss4]? v:nil}.compact %>
  <%end %>
  <%end %>
<hr class="profit-split-hr">
<div class="row">
  <div class="col-md-12">
    <div class="col-md-1 bullet-top">
      <span class="bullet-label"></span>
    </div>
    <div class="form-group col-md-1">
      <div class="row">
        <label class="h5">Owner's ID</label>
      </div>
    </div>
    <div class="col-md-2">
      <%=f.file_field(:owner_id_card, multiple: true,class: @owner_id_card.present? ? 'btn input-file image_have':'btn input-file',  accept:".doc,.rtf,.xlsx,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,image/x-png,image/gif,image/jpeg,application/pdf,application/csv, .csv",  data: { max_file_size: 10.megabytes}) %>
    </div>
    <div class="col-md-8 user_documentation_owner_id_card img-preview">
          <% if @images.present? %>
            <% @images.each do |image| %>
              <% if image.image_type == Documentation.types[:owner_id_card] %>
                <div class="row selected-file">
                  <div class="col-md-12">
                <div class="col-sm-3"></div>
                <div class="col-sm-5 span-color">
                  <% if ['image/jpeg','image/jpg','image/png','image/gif'].include?(image.document_content_type) %>
                    <span class="<%=image.id %>"><%= image.document_file_name.present? ? image.document_file_name.truncate(25, :omission => "...#{image.document_file_name[-5,image.document_file_name.length]}") : '' %></span>
                  <% else %>
                    <a href="<%= image.document.url %>" class="<%=image.id %> span-color"><%= image.document_file_name.present? ? image.document_file_name.truncate(25, :omission => "...#{image.document_file_name[-5,image.document_file_name.length]}") : '' %></a>
                  <% end %>
                </div>
                <div class="col-sm-4 top-padding <%=image.id %>">
                  <%= link_to '','https:'+image.document.url,class: 'fa fa-download fa-2x panel-heading', download:image.document, target: '_blank' %>
                  <%= link_to '','',id: image.id,class: 'fa fa-close fa-2x panel-heading',onclick: "$('#cover-spin').show(0);"%>
                </div>
                </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
    </div>
    <div class="help-block with-errors"></div>
  </div>
</div>
<hr class="profit-split-hr">
<div class="row">
  <div class="col-md-12">
    <div class="col-md-1 bullet-top">
      <span class="bullet-label"></span>
    </div>
    <div class="form-group col-md-1">
      <div class="row">
        <label class="h5">W-9</label>
      </div>
    </div>
    <div class="col-md-2">
      <%=f.file_field(:w9, multiple: true,class: @w9.present? ? 'btn input-file image_have':'btn input-file',  accept:".doc,.rtf,.xlsx,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,image/x-png,image/gif,image/jpeg,application/pdf,application/csv, .csv", data: { max_file_size: 10.megabytes}) %>
    </div>
    <div class="col-md-8 user_documentation_w9 img-preview">
          <% if @images.present? %>
            <% @images.each do |image| %>
              <% if image.image_type == Documentation.types[:w9] %>
             <div class="row selected-file">
              <div class="col-md-12">
                <div class="col-sm-3"></div>
                <div class="col-sm-5 span-color">
                  <% if ['image/jpeg','image/jpg','image/png','image/gif'].include?(image.document_content_type) %>
                    <span class="<%=image.id %>"><%= image.document_file_name.present? ? image.document_file_name.truncate(25, :omission => "...#{image.document_file_name[-5,image.document_file_name.length]}") : '' %></span>
                  <% else %>
                    <a href="<%= image.document.url %>" class="<%=image.id %> span-color"><%= image.document_file_name.present? ? image.document_file_name.truncate(25, :omission => "...#{image.document_file_name[-5,image.document_file_name.length]}") : '' %></a>
                  <% end %>
                </div>
                <div class="col-sm-4 top-padding <%=image.id %>">
                  <%= link_to '','https:'+image.document.url,class: 'fa fa-download fa-2x panel-heading', download:image.document, target: '_blank' %>
                  <%= link_to '','',id: image.id,class: 'fa fa-close fa-2x panel-heading',onclick: "$('#cover-spin').show(0);"%>
                </div>
                </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
    </div>
    <div class="help-block with-errors"></div>
  </div>
</div>
<hr class="profit-split-hr">
<div class="row">
  <div class="col-md-12">
    <div class="col-md-1 bullet-top">
      <span class="bullet-label "></span>
    </div>
    <div class="form-group col-md-1">
      <div class="row">
        <label class="h5">SS4/EIN</label>
      </div>
    </div>
    <div class="col-md-2">
      <%=f.file_field(:ein, multiple: true,class: @ein.present? ? 'btn input-file image_have':'btn input-file',  accept:".doc,.rtf,.xlsx,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,image/x-png,image/gif,image/jpeg,application/pdf,application/csv, .csv",  onchange: "validateFiles(this);", data: { max_file_size: 10.megabytes}) %>
    </div>
    <div class="col-md-8 user_documentation_ein  img-preview">
          <% if @images.present? %>
            <% @images.each do |image| %>
              <% if image.image_type == Documentation.types[:ein] || image.image_type == Documentation.types[:ss4] %>
            <div class="row selected-file">
              <div class="col-md-12">
                <div class="col-sm-3"></div>
                <div class="col-sm-5 span-color">
                  <% if ['image/jpeg','image/jpg','image/png','image/gif'].include?(image.document_content_type) %>
                    <span class="<%=image.id %>"><%= image.document_file_name.present? ? image.document_file_name.truncate(25, :omission => "...#{image.document_file_name[-5,image.document_file_name.length]}") : '' %></span>
                  <% else %>
                    <span class="<%=image.id %>"><a href="<%= image.document.url %>" class="<%=image.id %> span-color"><%= image.document_file_name.present? ? image.document_file_name.truncate(25, :omission => "...#{image.document_file_name[-5,image.document_file_name.length]}") : '' %></a></span>
                  <% end %>
                </div>
                <div class="col-sm-4 top-padding <%= image.id %>">
                  <%= link_to '','https:'+image.document.url,class: 'fa fa-download fa-2x panel-heading', download:image.document, target: '_blank' %>
                  <%= link_to '','',id: image.id,class: 'fa fa-close fa-2x panel-heading',onclick: "$('#cover-spin').show(0);"%>
                </div>
              </div>
            </div>
              <% end %>
            <% end %>
          <% end %>
    </div>
    <div class="help-block with-errors"></div>
  </div>
</div>

app/views/admins/merchants/_merchant.html.erb
<tr>
  <td><%= merchant.id %></td>
  <td><%= merchant.name %></td>
  <td><%= merchant.phone_number %></td>
  <td><%= merchant.owner_name %></td>
  <td><%= merchant.email %></td>
  <td>
    <% if merchant.oauth_apps.first.present? %>
      <div class="block_dd_css">
      <%= select_tag :is_block, options_for_select([['ACTIVE', false],['INACTIVE', true]], merchant.oauth_apps.first.is_block),
                     :'data-remote' => 'true',
                     :'data-url' => url_for(update_valid_app_path(merchant.oauth_apps.first.id)),
                     :prompt => false,
                     :required => true,
                     class: "btn btn-primary btn-sm dropdown-toggle",
                     data: {confirm: "Are you sure ?"}
      %>
      </div>
      <% else %>
      <div class="block_dd_css"> <strong>Incomplete Profile</strong></div>
    <% end %>
  </td>
    <td>
      <% if merchant.oauth_apps.first.present? %>
      <div class="dropdown" id="dropdownid">
        <a class="block_dd_css" type="button" data-toggle="dropdown">●●●
        </a>
        <ul class="dropdown-menu bg_white">
          <li><%= link_to("Edit", edit_merchant_path(merchant),:remote => true  ,:class => "btn btn-sm editModel", "data-toggle" => "modal" ) %></li>
          <li><%= link_to('Locations',merchant_id_locations_path(merchant),class: 'btn btn-sm') %></li>
          <li><a class="locs_id btn btn-sm" id=<%= merchant.id %>>API Keys</a></li>
        </ul>
      </div>
      <% end %>
    </td>
</tr>

app/views/admins/merchants/fee.html.erb
<%= render :layout => 'merchant_profile' do |f| %>
  <%= f.fields_for :location, Location.new do |form| %>
  <%= form.simple_fields_for :fee do |fee| %>
  <h5 class="card-title m-fee-st">Fees</h5>
    <%= render partial: 'admins/merchants/fee', locals: {:f => fee}  %>
  <% end %>
  <% end %>
<% end %>
<%= javascript_include_tag "admins/merchant/fee.js" %>

app/views/admins/merchants/new.html.erb
<%#= form_for User.merchant.new , :url => merchants_path , :html => { :multipart => true }, method: :post  do |f| %>
<div class="title-block">
  <h1 class="title text-capitalize new-st">
    New Merchant
  </h1>
</div>
<%#= form_for User.new, url: wizard_path(:id => :new) do |f| %>

  <%#= yield f %>

  <div class="actions">
    <%= link_to "Continue", next_wizard_path(:id => :corporate) %>
  </div>
<%# end %>
<%#= render 'admins/merchants/merchant_profile'%>
<%# end %>