config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'messages/index'
    get 'messages/show'
    resources :emails do
      collection do
        get :export
        get :delete_schedule
        post :resend
        get :resend_email
      end
    end
  end

  require 'sidekiq/web'

  root :to => 'home#index'
  
  # ActionCable mounted for microservice comms
  mount ActionCable.server => '/cable'
  # Sidekiq mounted for background queueing dashboard
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'contacts/message'
  get 'update_valid/:id', to: 'admins#update_valid', as: :update_valid_app

  resources :checkout, module: 'checkout', only: [:index,:new] do
    collection do
      get 'error'
      post 'get_card_information'
      get 'documentation'
      get 'select_payment_options'
      get 'select_payment_options_post'
      post 'checkout'
      post 'invoice_rtp_request'
      post 'test_webhook'
      get 'invoice_rtp_checkout'
    end
  end


  namespace :customers do
    resources :messages , only: [:index,:show,:new] do
      collection do
        post :save_chat
      end
    end
    resources :orders , only: [:index,:show]
    resources :disputes, only: [:index,:new,:create,:show] do
      collection do
        get 'update_tracker/:id' , to: "disputes#update_tracker" , as: :update_tracker
        get 'mail_generate_label/:id' , to: "disputes#mail_generate_label" , as: :mail_generate_label
        get 'update_notification/:id' , to: "disputes#update_notification" , as: :update_notification
      end
      resources :dispute_requests , only: [:update,:create]
    end
    resources :profiles , only: [:edit,:update] , path: '' do
      collection do
        get 'form_validate' , to: "profiles#form_validate"
      end
    end
  end


  resources :transactions, module: 'checkout'  do
    collection do
      post 'payment'
      post 'rtp_payment'
      get 'rtp_payment1'
      post 'rtp_payment_hook'
      get 'status'
    end
  end

  namespace :admins do
    resources :load_balancers, only: [:index, :new, :create, :edit, :update, :show] do
      collection do
        get 'update_load_balancer'
        post 'update_load_balancer'
      end
    end

    # get 'sales/index' , to: 'sales#index'
    # get 'sales/batch_detail' , to: 'sales#batch_detail'
    # get 'sales/qr_refund' , to: 'sales#qr_refund'
    # get 'sales/edit' , to: 'sales#edit'
    # get 'sales/refund_all' , to: 'sales#refund_all'
    # put 'sales/update' , to: 'sales#update'
    get 'locations/check_location_name'
    get 'mechant_bank_apis/index'
    get 'mechant_bank_apis/boltpay'
    get 'mechant_bank_apis/new'
    post 'mechant_bank_apis/create'
    get 'mechant_bank_apis/show'
    get 'mechant_bank_apis/edit'
    post 'mechant_bank_apis/update'
    get 'merchants/country_data'

    get :customer_disputes, to: "customer_disputes#customer_disputes"
    resources :customer_disputes, only: [:show]
    resources :messages, only: [:index,:show]
    # ---------sub-merchant-Admin Portal---------------
    get 'merchants/new_sub_merchant' , to:  'merchants#new_sub_merchant'
    post 'merchants/create_sub_merchant' , to:  'merchants#create_sub_merchant'
    get 'merchants/edit_sub_merchant' , to: 'merchants#edit_sub_merchant'
    put 'merchants/update_sub_merchant' , to: 'merchants#update_user_sub_merchant'
    get 'merchants/destroy_sub_merchant' , to: 'merchants#destroy_sub_merchant'

    resources :maxmind, only: [:show] do
      collection do
        get :edit
        post :update
      end
    end
    # ---------sub-merchant-Admin Portal---------------

    resources :plugin

    resources :admin_users do
        collection do
            get :get_data
            get :profile
        end
    end
    resources :affiliate_programs
    resources :reports, only: [] do
      collection do
        get :old_reports
        get :run_report
        get :autocomplete_location
        get :autocomplete_location_WR
        get :autocomplete_user
        get :autopopulate_partner
        get :autopopulate_affiliates
        post :generate_report
        get :generate_report
        get :search_user
        kinds = %w|chargeback sale gateway merchant wallet withdrawal terminal_id affiliate_program cbk_detail|
        get "index/:kind" => "reports#index", constraints: {kind: Regexp.new(kinds.join('|'))}
      end
    end

    resources :ach_gateways, only: [:index,:create,:edit,:update,:new] do
      collection do
        get 'archive_ach_gateway/:id', to:  "ach_gateways#archive", :as => :archive_ach_gateway
        get :archived_ach_gateways
        get 'block_ach_gateways/:id', to:  "ach_gateways#block_ach_gateways", :as => :block_ach_gateways
        get 'push_to_card' , to: "ach_gateways#push_to_card" , :as => :push_to_card
        get 'check' , to: "ach_gateways#check" , :as => :check
        get 'archive_push_to_card_gateway/:id', to:  "ach_gateways#archive", :as => :archive_push_to_card_gateway
        get 'archive_check_gateway/:id', to:  "ach_gateways#archive", :as => :archive_check_gateway
        get :archived_push_to_card_gateways
        get :archived_check_gateways
        get :check_gateway_existance
        # get :getverticaltype
        # get :getverticaltypenew
        # post :postverticaltype
      end
    end

    resources :slot_gateways, only: [:index,:create,:edit,:update,:new] do
      collection do
        get 'archive_slot_gateway/:id', to:  "slot_gateways#archive", :as => :archive_slot_gateway
        get :archived_slot_gateways
        get :validate_slot
        get :slot_management
        get :reset_slot_setting
        post :post_slot_management
        get 'block_slot_gateways/:id', to:  "slot_gateways#block_slot_gateways", :as => :block_slot_gateways
      end
    end

    resources :total_funds, only: [:index] do
      collection do
        get 'total_funds_search'
      end
    end


    resources :payment_gateways, only: [:index,:create,:edit,:update,:new] do
      collection do
        get 'archive_gateway/:id', to:  "payment_gateways#archive", :as => :archive_gateway
        get :archived_gateways
        get :unique_descriptor
        get 'block_gateways/:id', to:  "payment_gateways#block_gateways", :as => :block_gateways
        get 'specific_merchant', to:  'payment_gateways#specific_merchant'
        get :getverticaltype
        get :getverticaltypenew
        post :postverticaltype
        get :new_descriptor
        post :archive_descriptor
        post :create_descriptor
        get :old_gateways
      end
    end

    get 'transfers/index'
    get 'transfers/get_location_wallets'
    get 'transfers/get_merchant_location'
    get 'transfers/get_users'
    get 'transfers/get_user_details'
    post 'transfers/transfer_post'
    get 'transfers/get_wallet_name'
    resources :transfers, only: [] do
      get :autocomplete_user_name, on: :collection
    end

    resources :buy_rate, except: [:show] do
      collection do
        get :verify_admin
        get :verify_admin_password
      end
    end

    get 'buy_rate/getAgents'
    get 'buy_rate/getAffiliates'
    get 'buy_rate/getUsers'
    get 'buy_rate/getMerchantLocations'

    # ach
    get 'batch_checks', to: 'checks#batch_checks' , as: :batch_checks
    get 'check_batches', to: 'checks#check_batches' , as: :check_batches
    post 'check_batch_date', to: 'checks#check_batch_date' , as: :check_batch_date
    get :ach_index, :to => 'ach#index'
    get :under_review, :to => 'checks#under_review'
    get 'bulk_status_change', to: 'checks#bulk_status_change' , as: :bulk_status_change

    # post :instant_pay_batch_date, :to=>'instant_pay#instant_pay_batch_date',as: :member

    post :ach_batch_date, :to=>'instant_pay#ach_batch_date',as: :member
    get :ach_approved, :to => 'ach#ach_approved'
    get 'ach/new',  :to => 'ach#new'
    get 'ach/:id/approve', to: 'ach#approve',as: 'ach_approve'
    get 'ach/batches'
    get 'selected_locations', :to => 'ach#selected_locations'
    get 'location_data', :to => 'ach#location_data'
    # post 'create_ach', :to => 'ach#create_ach'

    #instant pay
    get :instant_pay_verify_phone_number, :to => 'instant_pay#verify_phone_number'
    get :instant_pay_verification, :to => 'instant_pay#verification'
    get :instant_pay_index, :to => 'instant_pay#index'
    # post :instant_pay_index, :to => 'instant_pay#index'
    post :instant_pay_batch_date, :to=>'instant_pay#instant_pay_batch_date',as: :instant_member
    get :approve_debit_card_deposit, :to => 'checks#approve_debit_card_deposit'
    get 'instant_pay/new',  :to => 'instant_pay#new'
    get :instant_pay_approved, :to => 'instant_pay#instant_pay_approved'
    get 'instant_pay/:id/approve', to: 'instant_pay#approve',as: 'instant_approve'
    put :update_name, :to => 'instant_pay#update_name'
    put 'instant_pay/update', :to => 'instant_pay#update', as: :instant_pay_update
    get 'instant_pay/batches'
    get 'instant_pay/selected_locations', :to => 'instant_pay#selected_locations'
    get 'instant_pay/location_data', :to => 'instant_pay#location_data'
    # post 'create_instant_pay', :to => 'instant_pay#create_instant_pay'
    get 'instant_pay/bulk_status_change', to: 'instant_pay#bulk_status_change' , as: :instant_pay_bulk_status_change

    #= instant_ach
    get :instant_ach_verify_phone_number, :to => 'instant_ach#verify_phone_number'
    get :instant_ach_verification, :to => 'instant_ach#verification'
    get :instant_ach_index, :to => 'instant_ach#index'
    post :instant_ach_export, :to => 'instant_ach#export'
    post :instant_ach_batch_date, :to=>'instant_ach#instant_ach_batch_date',as: :instant_ach_member
    get :instant_ach_approved, :to => 'instant_ach#instant_ach_approved'
    get :d_date, :to => 'instant_ach#d_date'
    put :update_recipient, :to => 'instant_ach#update_recipient'
    get 'instant_ach/new',  :to => 'instant_ach#new'

app/controllers/admins/maxmind_controller.rb
class Admins::MaxmindController < AdminsController
  before_action :check_admin

  def show
    @minfraud_result = MinfraudResult.find(params[:id])
    @minfraud_insight = @minfraud_result.insight_detail
    render partial: 'show'
  end

  def edit
    @moderate_risk = AppConfig.where(key: AppConfig::Key::ModerateRiskMaxMind).first_or_create(stringValue: "0.0")
    @high_risk = AppConfig.where(key: AppConfig::Key::HighRiskMaxMind).first_or_create(stringValue: "0.0")
    @approve_manual_review = AppConfig.where(key: AppConfig::Key::ApproveManualReviewDays).first_or_create(stringValue: "0")
  end

  def update
    if params[:high_risk]
      @high_risk = AppConfig.where(key: AppConfig::Key::HighRiskMaxMind).first
      @high_risk.update(stringValue: params[:high_risk])
      flash[:notice] = "Updated Successfully!"
    elsif params[:moderate_risk]
      @moderate_risk = AppConfig.where(key: AppConfig::Key::ModerateRiskMaxMind).first
      @moderate_risk.update(stringValue: params[:moderate_risk])
      flash[:notice] = "Updated Successfully!"
    elsif params[:approve_manual_review]
      @approve_manual_review = AppConfig.where(key: AppConfig::Key::ApproveManualReviewDays).first
      @approve_manual_review.update(stringValue: params[:approve_manual_review])
      flash[:notice] = "Updated Successfully!"
    else
      flash[:error] = "Something Went Wrong."
    end
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/merchant/apps_controller.rb
class Merchant::AppsController < Merchant::BaseController

  def index
    @heading = 'Apps'
    if current_user.merchant_id.present? 
      @apps=OauthApp.where(user_id: current_user.merchant_id).per_page_kaminari(params[:page]).per(10).order("id DESC")
    else
      @apps=OauthApp.where(user_id: current_user.id).per_page_kaminari(params[:page]).per(10).order("id DESC")
    end
  end

  def create
    @app = OauthApp.new(app_params)
    if current_user.merchant_id.present? && current_user.submerchant_type == "admin_user"
      @app.user_id = current_user.merchant_id
    else
      @app.user_id = current_user.id
    end
    @app.key = 'ID' + random_token
    @app.secret = 'SE' + random_token
    @app.token = random_token
    if @app.save
      flash[:notice] = I18n.t 'merchant.controller.app_created'
      if current_user.MERCHANT?
        redirect_back(fallback_location: root_path)
      else
        redirect_back(fallback_location: root_path)
      end
    else
      flash[:notice] = I18n.t 'merchant.controller.app_saving'
      redirect_back(fallback_location: root_path)
    end
  end

  def new
  end

  def edit
  end

  def update
    @heading = "Application Settings"
    @app = OauthApp.find(params[:id])
    @app.update(key: 'ID' + random_token,secret:  'SE' + random_token ,token: random_token)
    respond_to :js
  end

  def show
    @heading = "Application Settings"
    @app = OauthApp.find params[:id]
  end

  def destroy
    @app = OauthApp.find(params[:id])
    if @app.destroy
      flash[:notice] = I18n.t 'merchant.controller.app_del'
      redirect_to root_path
    end
  end

  def show_app
    @app = OauthApp.find(params[:user_id])
    render partial: 'shared/app_modal', locals: { user: @app }
  end

  def update_valid
    @app = OauthApp.find(params[:id])
    @app.is_block = params[:is_block]
    @app.save(:validate => false)
  end

  private

  def app_params
    params.require(:oauth_app).permit(:name, :description, :redirect_uri, :website, :privacy_url, :tos, :organization_name, :organization_web)
  end
end

app/controllers/merchant/bank_controller.rb
class Merchant::BankController < Merchant::BaseController

  def index
    @banks =  BankDetail.all.order(id: :desc)
    @iv       = 'a2xhcgAAAAAAAAAA'
    @password = Digest::SHA256.digest("#{ENV['BANK_ECRYPTION_CODE']}")
    #bank = BankDetail.first
  end

  def create
    bank_name = params[:bank_name]
    account_name = params[:account_name]
    account_no = params[:account_no]
    routing_no = params[:routing_no]
    account_digits = account_no.split(//).last(4).join
    routing_digits = routing_no.split(//).last(4).join
    enc_account_no = AESCrypt.encrypt("#{ENV['BANK-ENCRYPTION-CODE']}",  account_no)
    enc_routing_no = AESCrypt.encrypt("#{ENV['BANK-ENCRYPTION-CODE']}",  routing_no)
    BankDetail.create! bank_name: bank_name, account_name: account_name, account_no: enc_account_no, routing_no: enc_routing_no, account_digit: account_digits, routing_digit: routing_digits
    flash[:success] = I18n.t 'merchant.controller.bank_detail'
    redirect_to merchant_bank_index_path
  end
end

app/controllers/merchant/customer_disputes_controller.rb
class Merchant::CustomerDisputesController < Merchant::BaseController

  def index
    @customer_disputes = @user.disputes_as_merchant
  end

  def show
    @customer_dispute = CustomerDispute.find(params[:id])
    @transaction = @customer_dispute.dispute_transaction
    @tracker = @transaction.tracker
    @customer = @customer_dispute.customer
    @dispute_request_first = @customer_dispute.dispute_requests.first
    @dispute_requests_last = @customer_dispute.dispute_requests.last
    @merchant_offer = @customer_dispute.dispute_requests.where(request_type: "merchant_offer").first
    @final_merchant_offer = @customer_dispute.dispute_requests.where(request_type: "merchant_final_offer").last
    @pending_counter_offer = @customer_dispute.dispute_requests.where(user_id: @customer_dispute.customer_id,status: "pending",title: "Counteroffer").last
    @customer_offer =  @customer_dispute.dispute_requests.where(request_type: "counter_offer").last
    @return_to_sender = @customer_dispute.dispute_requests.where(request_type: "return_to_sender").last
    # TODO there should be only 1 pending dispute_requests
    render partial: 'show'
  end

end

app/controllers/merchant/plugins_controller.rb
class Merchant::PluginsController < Merchant::BaseController
  layout 'merchant'
  def index
    @plugins=Asset.all
  end
end

app/views/merchant/maxmind/index.html.erb
<div class="box">
  <div class="box-header with-border">
    <div class="row">
      <%=form_tag merchant_maxmind_index_path, method: :get, class:'search_transactions',  autocomplete: "off" do  %>
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-6">
              <% @risk_evaluation_status.each do |box| %>
                <%
                    checked = false
                    if params[:risk_status].present? && params[:risk_status].include?(box[:value])
                      checked = true
                    end
                %>
                <div class="checkbox">
                  <%= check_box_tag 'risk_status[]', box[:value], checked -%>
                  <%= box[:view] -%>
                </div>
              <%end %>
            </div>
            <div class="col-md-6">
              <div class="row">

                <div class="col-md-12">
                  <div class="form-group" id="date_parent">
                    <label for="id">Date</label>
                    <input type='text' name="query[date]"  id="maxmind_date_range_picker" class="datepicker form-control" value="<%= params[:query].present? ? params[:query]["date"] : "" %>"  />
                    <!--                    <input type="hidden" name="offset" value="<%#= params[:offset]%>"  />-->
                    <input type="hidden" name="offset" value="<%=params[:query].present? && params[:query]['offset'].present? ? params[:query]['offset'] : Time.now.in_time_zone(cookies[:timezone]).strftime("%z")%>"  />
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
        <div class="col-md-12 text-right">
          <input type="hidden" name="trans" value="<%= params[:trans]  if  params[:trans].present? %>"  />
          <button type="submit" class="btn btn-success btn-sm search_button">Search</button>
          <input type="hidden" name="tx_maxmind_filter" id="tx_maxmind_filter" value="<%= params[:tx_maxmind_filter].present? ? params[:tx_maxmind_filter] : "" %>"  />
        </div>
      <%end %>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-6">
            <h3 class="box-title"> Manual Review Transactions</h3>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="box-body">
    <div class="row filter_container">
      <div class="col-md-12">
        <span id="show">Show</span>
        <span id="show_left">
              <%= form_tag merchant_maxmind_index_path, method: :get , id: 'maxmind_filter'  do  %>
                 <%= select_tag "tx_maxmind_filter", options_for_select(@filters.map{|v|[v]}, selected: params[:tx_maxmind_filter].present? ? params[:tx_maxmind_filter] : "10"),
                                :prompt => false,
                                :required => true,
                                class: "form-control form-control-sm",
                                data: {confirm: "Are you sure ?"}
                 %>
            <% if params[:query].present? %>
                            <input type="hidden" name="query[date]" value="<%= params[:query][:date]  if  params[:query][:date].present? %>"  />
                            <input type="hidden" name="risk_status" value="<%= params[:risk_status] if  params["risk_status"].present? %>"  />
                        <% end %>
              <% end %>
            </span>
        <span id="entries">Entries</span>
      </div>
      <div class="col-md-12"></div>
    </div>
    <div class="col-md-12">
      <div id="manual_review_transaction_table">
        <table class="table table-striped">
          <thead>
          <th>Status</th>
          <th>WebSite</th>
          <th class="">Order ID</th>
          <th>Date</th>
          <th>Customer Name</th>
          <th>Amount</th>
          <th>
            RiskScore
            <div class="tooltip">
              <i class='fa fa-info-circle'aria-hidden='true' id="tool_tip"></i>
              <span class="tooltiptext riskscore"><%= I18n.t('maxmind.hover_text') %></span>
            </div>
            <%#= link_to "<i class='fa fa-exclamation-circle'></i>".html_safe, "#", :title => I18n.t('maxmind.hover_text') %>
          </th>
          <th></th>
          <th></th>
          </thead>
          <tbody>
          <% if @manual_review_transactions.count > 0 %>
            <% @manual_review_transactions.each do |t| %>
              <tr  id="on_click1" class="show-dynamic-modal" data-url-path= "<%= merchant_maxmind_path(t.minfraud_result.id) %>" data-modal-selector=".show-detail" data-modal-container-selector="#detail-transaction" data-method = "GET">
                <td class="status_btn"><%= maxmind_minfraud_detail_status(t.minfraud_result).html_safe %></td>
                <td><%= t.minfraud_result.present? ? maxmind_minfraud_website_url(t.minfraud_result) : "--" %></td>
                <!--              <td> <%#= t.seq_transaction_id.present? ? t.seq_transaction_id[0..5] : nil %></td>-->
                <!--              <td> <%#= t.receiver_name.present? ? t.receiver_name :  t.receiver.try(:name) %></td>-->
                <td> <%= t.minfraud_result.insight_detail["id"] %></td>
                <!--              <td><%#= "****#{t.last4}" %></td>-->
                <td class="timeUtc"> <%= t.created_at.strftime("%Y-%m-%d %H:%M:%S %z") %></td>
                <td> <%= t.sender_name.present? ? t.sender_name :  t.sender.try(:name) %></td>
                <td><%= number_with_precision(number_to_currency(t.total_amount), precision: 2) %></td>
                <td> <%= t.minfraud_result.try(:risk_score) %></td>
                <% if @minfraud_result.present? && @minfraud_result.qc_action == TypesEnumLib::RiskType::PendingReview %>
                  <td id="on_click1" class="hit-dynamic-href" data-url-path= "<%= merchant_maxmind_path(t.minfraud_result.id, new_action: "r") %>" data-modal-selector=".show-detail" data-modal-container-selector="#detail-transaction" data-method = "PUT" >
                    <i class="fa fa-reply"></i>
                    <%#= link_to('Reject',merchant_maxmind_path(t.minfraud_result.id, new_action: "r"), method: :post, class: 'btn btn-sm') %>
                  </td>
                  <td id="on_click1" class="hit-dynamic-href" data-url-path= "<%= merchant_maxmind_path(t.minfraud_result.id, new_action: "a") %>" data-modal-selector=".show-detail" data-modal-container-selector="#detail-transaction" data-method = "PUT" >
                    <i class="fa fa-check-circle"></i>
                  </td>
                <% else %>
                  <td></td>
                  <td></td>
                <% end %>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="9" id="no_data">Data Not Found</td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <%#= paginate @manual_review_transactions, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-small pagination-centered pull-right"%>
      </div>
      <div class="col-md-12 tx_pagination">
        <div class="row">
          <div class="col-md-4">
            <span>Showing <%=@manual_review_transactions.try(:size)%> of <%= @manual_review_transactions.total_count %> records</span>
          </div>
          <div class="col-md-8">
            <div class="text-align-right-ach" id="paginator">
              <% if @manual_review_transactions.present? %>
                <%= paginate @manual_review_transactions, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-small pagination-centered pull-right padd"%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<section id="detail-transaction"></section>